.TH MAPPER 1 2014-04-27 OpenOrienteering

.SH NAME
Mapper \- orienteering map drawing software

.SH SYNOPSIS
.B Mapper
.RI [ FILES ]

.SH DESCRIPTION
OpenOrienteering Mapper is an orienteering map drawing software.
It comes with predefined symbol sets implementing the IOF standards
ISOM (1:15000, 1:10000) and ISSOM (1:5000, 1:4000).
But it is easy to implement other symbol sets.

.SH OPTIONS
This program takes map file names as options.

.SH AUTHOR
This manual page was written by Kai Pastor <dg0yt@darc.de>.

.SH "REPORTING BUGS"
Report bugs in the OpenOrienteering ticket system:
.br
<http://sourceforge.net/p/oorienteering/tickets/>

.SH COPYRIGHT
Copyright \(co 2014 The OpenOrienteering developers
.br
License GPLv3: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
Extended documentation for
.B Mapper
is available from the program's help menu and also online in the
OpenOrienteering user wiki:
.br
<http://sourceforge.net/p/oorienteering/wiki/Home/>
